name: Dapr Root Website

on:
  workflow_dispatch:
  push:
    branches:
      - v1.11
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v1.11

jobs:
  build:
    name: Build Hugo Website
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      SWA_BASE: 'proud-bay-0e9e0e81e'
      HUGO_ENV: production
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: 0.102.3
          extended: true
      - name: Setup Docsy
        run: |
          cd daprdocs
          git submodule update --init --recursive
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
      - name: Build Hugo Website
        run: |
          cd daprdocs
          git config --global --add safe.directory /github/workspace
          if [ $GITHUB_EVENT_NAME == 'pull_request' ]; then
            STAGING_URL="https://${SWA_BASE}-${{github.event.number}}.westus2.azurestaticapps.net/"
          fi
          hugo ${STAGING_URL+-b "$STAGING_URL"}
      - name: Upload Hugo artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hugo_build
          path: ./daprdocs/public/
          if-no-files-found: error

  deploy:
    name: Deploy website
    needs: ['build']
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Download Hugo artifacts
        uses: actions/download-artifact@v3
        with:
          name: hugo_build
          path: site/
      - name: Deploy staging site
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_BAY_0E9E0E81E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "site/"
          api_location: "site/" 
          output_location: ""
          skip_app_build: true

  close_staging_site:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_BAY_0E9E0E81E }}
          action: "close"
